---
- name: Ensure Neutron database exists
  mysql_db:
    name: neutron
    state: present
  become_user: root

- name: Grant privileges on Neutron database to 'neutron'@'localhost'
  mysql_user:
    name: neutron
    host: localhost
    password: 'neutronpass'
    priv: 'neutron.*:ALL'
    state: present
  become_user: root

- name: Grant privileges on Neutron database to 'neutron'@'%'
  mysql_user:
    name: neutron
    host: '%'
    password: 'neutronpass'
    priv: 'neutron.*:ALL'
    state: present
  become_user: root

- name: Sourcing the admin credentials
  command: source /home/cserver/admin-openrc
  failed_when: false
  no_log: true

- name: Creating neutron user
  become_user: root
  expect:
    command: openstack user create --domain default --password-prompt neutron
    reponses:
      "User Password": neutronpass
      "Repeat User Password": neutronpass
  failed_when: false
  no_log: true

- name: Adding admin roles to the neutron user
  command: openstack role add --project service --user neutron admin
  failed_when: false
  no_log: true

- name: Creating neutron service entity
  command: openstack service create --name neutron --description "OpenStack Networking" network
  failed_when: false
  no_log: true

- name: Creating the network service API endpoints
  shell: |
    openstack endpoint create --region RegionOne network public http://controller:9696
    openstack endpoint create --region RegionOne network internal http://controller:9696
    openstack endpoint create --region RegionOne network admin http://controller:9696
  failed_when: false
  no_log: true

- name: Installing neutron and its dependencies
  yum:
    name:
      - openstack-neutron 
      - openstack-neutron-ml2 
      - openstack-neutron-linuxbridge 
      - ebtables

- name: Editing neutron config file
  copy:
    src: neutron.conf
    dest: /etc/neutron/neutron.conf
    owner: root
    group: neutron
    mode: 0640

- name: Editing ml2_conf.ini file
  copy:
    src: ml2_conf.ini
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    owner: root
    group: neutron
    mode: 0640

- name: Editing neutron config file
  copy:
    src: linuxbridge_agent.ini 
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini 
    owner: root
    group: neutron
    mode: 0640

- name: Editing neutron config file
  copy:
    src: dhcp_agent.ini
    dest: /etc/neutron/dhcp_agent.ini
    owner: root
    group: neutron
    mode: 0640

- name: Configuring metadata_agent.ini file
  copy:
    src: metadata_agent.ini
    dest: /etc/neutron/metadata_agent.ini
    owner: root
    group: neutron
    mode: 640

- name: Configuring nova.conf file
  copy:
    src: nova.conf
    dest: /etc/nova/nova.conf
    owner: root
    group: nova
    mode: 640

- name: Creating a link
  command: ln -s /etc/neutron/plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini
  failed_when: false
  no_log: true

- name: Populating the database
  become_user: root
  command: su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron
  failed_when: false
  no_log: true

- name: Restarting the nova-api service
  service:
    name: openstack-nova-api.service
    state: restarted
  failed_when: false
  no_log: true

- name: Starting and enabling the Networking services
  service:
    name: 
      - neutron-server.service
      - neutron-linuxbridge-agent
      - neutron-dhcp-agent
      - neutron-metadata-agent
    state: started
    enabled: true 
  failed_when: false
  no_log: true
